WebMVC/Areas/Admin/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [Authorize(AuthenticationSchemes = "Admin")]
    public class ManagerController : Controller
    {
        // GET: ManagerController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ManagerController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ManagerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManagerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ManagerController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ManagerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ManagerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ManagerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebMVC/Controllers/ContactPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebMVC.Controllers
{
    public class ContactPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Security.Claims;

namespace WebMVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly string ApiUrl = "";
        public LoginController()
        {
            _httpClient = new HttpClient();
            var typeClient = new MediaTypeWithQualityHeaderValue("application/json");
            _httpClient.DefaultRequestHeaders.Accept.Add(typeClient);
            ApiUrl = "https://localhost:7274/api/LoginAPI";
        }
        // GET: LoginController
        public ActionResult Index()
        {
            if (!Request.Cookies.ContainsKey("userName"))
            {
                return View();
            }
            return RedirectToAction("", "Home");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(string username, string password)
        {
            HttpResponseMessage responseMessage = await _httpClient.GetAsync($"{ApiUrl}/{username}/{password}");
            if (responseMessage.IsSuccessStatusCode)
            {
                Response.Cookies.Append("userName", "Admin");
                var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, username),
                        new Claim(ClaimTypes.Role,"Admin")
                    };
                var identity = new ClaimsIdentity(claims, "Admin");
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync("Admin", principal, new AuthenticationProperties()
                {
                    IsPersistent = true
                });
                //    var routeValues = new RouteValueDictionary
                //{
                //    {"area","Admin" },
                //    {"returnURL",Request.Query["ReturnURL"] }
                //};
                //return RedirectToAction("Index", "Home", routeValues);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Incorrect password or email or no account.");
            }
            throw new ArgumentException("Incorrect password or email or no account.");
        }
        #region Logout
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("Admin");
            Response.Cookies.Delete("userName");
            return RedirectToAction("Index", "Home");
        }
        #endregion
        // GET: LoginController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LoginController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoginController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LoginController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoginController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebMVC/Controllers/NewsPageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ObjectBussiness;
using System.Net.Http.Headers;
using System.Text.Json;
using X.PagedList;

namespace WebMVC.Controllers
{
    public class NewsPageController : Controller
    {
        // GET: NewsPageController
        private readonly HttpClient _httpClient = null;
        private string NewsApiUrl = "";
        public NewsPageController()
        {
            _httpClient = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            _httpClient.DefaultRequestHeaders.Accept.Add(contentType);
            NewsApiUrl = "https://localhost:7274/api/NewsControllerApi";
        }
        // GET: NewsController
        public async Task<IActionResult> Index(int? page)
        {
            HttpResponseMessage res = await _httpClient.GetAsync(NewsApiUrl);
            string strData = await res.Content.ReadAsStringAsync();
            var option = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
            List<News> news = JsonSerializer.Deserialize<List<News>>(strData, option);
            int pageNumber = (page ?? 1); // Nếu page là null, sử dụng trang 1.
            int pageSize = 3; // 
            IPagedList<News> pagedNews = news.ToPagedList(pageNumber, pageSize);
            return View(pagedNews);
        }
        // GET: NewsController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            HttpResponseMessage responseMessage = await _httpClient.GetAsync($"{NewsApiUrl}/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                var data = await responseMessage.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var news = JsonSerializer.Deserialize<News>(data, options);
                return View(news);
            }
            else
            {
                return View("Error", new { message = $"Error fetching news details: {responseMessage.StatusCode}" });
            }
        }
    }
}

WebMVC/Views/Shared/Aside.cshtml
<aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="@Url.Action("","Manager")">
            <img src="~/Admin/images/eco power (1).png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold">Company Management</span>
        </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="~/Admin/Manager">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Home">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">User View</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="~/Admin/QuestionAdmin">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Question</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="~/Admin/ExamAdmin">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Exam</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="~/Admin/NewsAdmin">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">News</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="~/Admin/NewsCategory">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">News Category</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="./pages/virtual-reality.html">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-app text-info text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Virtual Reality</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="./pages/rtl.html">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">RTL</span>
                </a>
            </li>
            <li class="nav-item mt-3">
                <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Account pages</h6>
            </li>
            @* <li class="nav-item">
                <a class="nav-link " href="./pages/profile.html">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Profile</span>
                </a>
            </li> *@
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("","Login")">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-single-copy-04 text-warning text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Login</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="~/Admin/RegisterAdmin/Register">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-collection text-info text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Register</span>
                </a>
            </li>
        </ul>
    </div>
</aside>

WebMVC/Views/Shared/Footer.cshtml
<footer class="templateux-footer bg-light">
    <div class="container">

        <div class="row mb-5">
            <div class="col-md-4 pr-md-5">
                <div class="block-footer-widget">
                    <h3>Contact</h3>
                    <p>Address:38 Yên Bái, Hải Châu 1, Hải Châu, Đà Nẵng 550000</p>
                    <p>Numberphone: 0852461608</p>
                </div>
            </div>

            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3">
                        <div class="block-footer-widget">
                            <h3>Learn More</h3>
                            <ul class="list-unstyled">
                                <li><a href="#">How it works?</a></li>
                                <li><a href="#">Useful Tools</a></li>
                                <li><a href="#">Pricing</a></li>
                                <li><a href="#">Sitemap</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="block-footer-widget">
                            <h3>Support</h3>
                            <ul class="list-unstyled">
                                <li><a href="#">FAQ</a></li>
                                <li><a href="#">Contact Us</a></li>
                                <li><a href="#">Help Desk</a></li>
                                <li><a href="#">Knowledgebase</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="block-footer-widget">
                            <h3>About Us</h3>
                            <ul class="list-unstyled">
                                <li><a href="@Url.Action("About","Home")">About Us</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Terms of Service</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="block-footer-widget">
                            <h3>Connect With Us</h3>
                            <ul class="list-unstyled block-social">
                                <li><a href="#" class="p-1"><span class="icon-facebook-square"></span></a></li>
                                <li><a href="#" class="p-1"><span class="icon-twitter"></span></a></li>
                                <li><a href="#" class="p-1"><span class="icon-github"></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div> <!-- .row -->

            </div>
        </div> <!-- .row -->

        <div class="row pt-5 text-center">
            <div class="col-md-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Code by ;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="text-danger icon-heart" aria-hidden="true"></i> by <a href="https://zalo.me/g/cfdynt409" target="_blank" class="text-primary">BẢO,AN,HƯNG</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div> <!-- .row -->

    </div>
</footer> <!-- .templateux-footer -->

WebMVC/Views/Shared/Header.cshtml
<header class="templateux-navbar" role="banner">

    <div class="container" data-aos="fade-down">
        <div class="row">

            <div class="col-3 templateux-logo">
                <a href="@Url.Action("","Home")" class="animsition-link">FcorePetroleum</a>
            </div>
            <nav class="col-9 site-nav">
                <button class="d-block d-md-none hamburger hamburger--spin templateux-toggle templateux-toggle-light ml-auto templateux-toggle-menu" data-toggle="collapse" data-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button> <!-- .templateux-toggle -->

                <ul class="sf-menu templateux-menu d-none d-md-block">
                    <li class="active">
                        <a href="@Url.Action("","Home")" class="animsition-link">Home</a>
                    </li>
                    <li><a href="@Url.Action("About","Home")" class="animsition-link">About</a></li>
                    <li><a href="@Url.Action("Index","NewsPage")" class="animsition-link">News</a></li>
                    <li><a href="@Url.Action("Index","ContactPage")" class="animsition-link">Contact</a></li>
                    @if (Context.Request.Cookies.ContainsKey("username"))
                    {
                        <li><a href="~/Admin/Manager" class="animsition-link">Manager</a></li>
                    }
                    @if (Context.Request.Cookies.ContainsKey("username"))
                    {
                        <li>
                            <a href="" class="animsition-link">Login/Register</a>
                            <ul>
                                <li><a href="@Url.Action("","Login")">Login</a></li>
                                <li><a href="~/Admin/RegisterAdmin/Register">Exam Register</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("","Login")">Login</a></li>
                    }
                </ul> <!-- .templateux-menu -->

            </nav> <!-- .site-nav -->


        </div> <!-- .row -->
    </div> <!-- .container -->
</header> <!-- .templateux-navba -->

WebMVC/Views/Shared/Navbar.cshtml
  <!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="javascript:;">Pages</a></li>
                <li class="breadcrumb-item text-sm text-white active" aria-current="page">@ViewData["Title"]</li>
            </ol>
            <h6 class="font-weight-bolder text-white mb-0">@ViewData["Title"]</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                <form class="input-group">
                    <button type="submit" class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></button>
                    <input name="SearchString" type="text" class="form-control" placeholder="Search name ..." required>
                </form>
            </div>
            <ul class="navbar-nav  justify-content-end">
                <li class="nav-item d-flex align-items-center">
                    <a href="@Url.Action("","Login")" class="nav-link text-white font-weight-bold px-0">
                        <i class="fa fa-user me-sm-1"></i>
                        <span class="d-sm-inline d-none">Login</span>
                    </a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a href="@Url.Action("Logout","Login")" class="nav-link text-white font-weight-bold px-0">
                        <i class="fa fa-sign-out-alt me-sm-1"></i>
                        <span class="d-sm-inline d-none">Logout</span>
                    </a>
                </li>
                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-white p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                        </div>
                    </a>
                </li>
                <li class="nav-item px-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-white p-0">
                        <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
                    </a>
                </li>
                <li class="nav-item dropdown pe-2 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-white p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-bell cursor-pointer"></i>
                    </a>
                    <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="javascript:;">
                                <div class="d-flex py-1">
                                    <div class="my-auto">
                                        <img src="~/Admin/assets/img/team-2.jpg" class="avatar avatar-sm  me-3 ">
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">
                                            <span class="font-weight-bold">New message</span> from Laur
                                        </h6>
                                        <p class="text-xs text-secondary mb-0">
                                            <i class="fa fa-clock me-1"></i>
                                            13 minutes ago
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="javascript:;">
                                <div class="d-flex py-1">
                                    <div class="my-auto">
                                        <img src="~/Admin/assets/img/small-logos/logo-spotify.svg" class="avatar avatar-sm bg-gradient-dark  me-3 ">
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">
                                            <span class="font-weight-bold">New album</span> by Travis Scott
                                        </h6>
                                        <p class="text-xs text-secondary mb-0">
                                            <i class="fa fa-clock me-1"></i>
                                            1 day
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item border-radius-md" href="javascript:;">
                                <div class="d-flex py-1">
                                    <div class="avatar avatar-sm bg-gradient-secondary  me-3  my-auto">
                                        <svg width="12px" height="12px" viewBox="0 0 43 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                            <title>credit-card</title>
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <g transform="translate(-2169.000000, -745.000000)" fill="#FFFFFF" fill-rule="nonzero">
                                                    <g transform="translate(1716.000000, 291.000000)">
                                                        <g transform="translate(453.000000, 454.000000)">
                                                            <path class="color-background" d="M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z" opacity="0.593633743"></path>
                                                            <path class="color-background" d="M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z"></path>
                                                        </g>
                                                    </g>
                                                </g>
                                            </g>
                                        </svg>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">
                                            Payment successfully completed
                                        </h6>
                                        <p class="text-xs text-secondary mb-0">
                                            <i class="fa fa-clock me-1"></i>
                                            2 days
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->