WebMVC/Areas/Admin/Controllers/NewsAdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ObjectBussiness;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using X.PagedList;

namespace WebMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewsAdminController : BaseAdminController
    {
        #region Variable
        private readonly HttpClient _httpClient = null;
        private string NewsApiUrl = "";
        PetroleumBusinessDBContext db;
        #endregion

        #region Constructor
        public NewsAdminController()
        {
            db = new PetroleumBusinessDBContext();
            _httpClient = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            _httpClient.DefaultRequestHeaders.Accept.Add(contentType);
            NewsApiUrl = "https://localhost:7274/api/NewsControllerApi";
        }
        #endregion
        // GET: NewsController
        #region Index
        public async Task<IActionResult> Index(int? page)
        {
            HttpResponseMessage res = await _httpClient.GetAsync(NewsApiUrl);
            string strData = await res.Content.ReadAsStringAsync();
            var option = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
            List<News> newsList = JsonSerializer.Deserialize<List<News>>(strData, option);

            int pageNumber = page ?? 1;
            int pageSize = 5;

            IPagedList<News> pagedNewsList = newsList.ToPagedList(pageNumber, pageSize);
            return View(pagedNewsList);
        }
        #endregion


        // GET: NewsController/Details/5
        #region Detail
        public async Task<IActionResult> Details(int id)
        {
            HttpResponseMessage responseMessage = await _httpClient.GetAsync($"{NewsApiUrl}/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                var data = await responseMessage.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var news = JsonSerializer.Deserialize<News>(data, options);

                return View(news);
            }
            else
            {
                return View("Error", new { message = $"Error fetching news details: {responseMessage.StatusCode}" });
            }
        }
        #endregion

        // GET: NewsController/Create
        #region Create
        public async Task<ActionResult> Create()
        {
            HttpResponseMessage responseMessage = await _httpClient.GetAsync("https://localhost:7274/api/NewsControllerApi/GetNewsCategory");
            var data = await responseMessage.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            List<NewsCategory> listCategory = JsonSerializer.Deserialize<List<NewsCategory>>(data, options);
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var item in listCategory)
            {
                selectList.Add(new SelectListItem { Value = item.CategoryID.ToString(), Text = item.CategoryName });
            }
            ViewBag.Items = selectList;
            return View();
        }

        // POST: NewsController/Create API//////////////////////////////////////////////////////
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewsImage n, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                Random random = new Random();
                News news = new News
                {
                    NewsID = random.Next(),
                    Title = n.Title,
                    Contents = n.Contents,
                    ShortContents = n.ShortContents,
                    DateSubmitted = n.DateSubmitted,
                    AccountID = n.AccountID,
                    CategoryID = n.CategoryID,
                };

                if (imageFile != null && imageFile.Length > 0)
                {
                    // Lấy tên tệp từ đường dẫn đầy đủ
                    var fileName = Path.GetFileName(imageFile.FileName);

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);
                    using (var stream = System.IO.File.Create(path))
                    {
                        await imageFile.CopyToAsync(stream);
                    }
                    // Gán chỉ tên tệp (không có đường dẫn đầy đủ)
                    news.Picture = fileName;
                }

                // Send data to API
                string strData = JsonSerializer.Serialize(news);
                var contentData = new StringContent(strData, System.Text.Encoding.UTF8, "application/json");
                HttpResponseMessage res = await _httpClient.PostAsync(NewsApiUrl, contentData);

                if (res.IsSuccessStatusCode)
                {
                    SetAlert("Successfully created new news", "success");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    // Log error or handle API response
                    ModelState.AddModelError("", "Creating new news failed");
                }
            }

            return View(n);
        }
        #endregion

        // GET: NewsController/Edit/5
        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            HttpResponseMessage res = await _httpClient.GetAsync($"{NewsApiUrl}/{id}");
            if (res.IsSuccessStatusCode)
            {
                string strData = await res.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                News n = JsonSerializer.Deserialize<News>(strData, options);
                HttpResponseMessage responseMessageList = await _httpClient.GetAsync("https://localhost:7274/api/NewsControllerApi/GetNewsCategory");
                var dataList = await responseMessageList.Content.ReadAsStringAsync();
                var optionsList = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                List<NewsCategory> newsCate = JsonSerializer.Deserialize<List<NewsCategory>>(dataList, optionsList);
                List<SelectListItem> selectListItems = new List<SelectListItem>();
                foreach (var item in newsCate)
                {
                    selectListItems.Add(new SelectListItem { Value = item.CategoryID.ToString(), Text = item.CategoryName });
                }
                ViewBag.Items = selectListItems;
                return View(n);
            }
            return NotFound();
        }


        // POST: NewsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, News n)
        {
            if (ModelState.IsValid)
            {
                string strData = JsonSerializer.Serialize(n);
                var contentData = new StringContent(strData, System.Text.Encoding.UTF8, "application/json");
                HttpResponseMessage res = await _httpClient.PutAsync($"{NewsApiUrl}/{id}", contentData);
                if (res.IsSuccessStatusCode)
                {
                    SetAlert("News updated successfully", "warning");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Error while call Web API");

                }
            }
            return View(n);
        }
        #endregion

        // GET: NewsController/Delete/5
        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            HttpResponseMessage res = await _httpClient.GetAsync($"{NewsApiUrl}/{id}");
            if (res.IsSuccessStatusCode)
            {
                string strData = await res.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                News n = JsonSerializer.Deserialize<News>(strData, options);
                return View(n);
            }
            return View();
        }

        // POST: NewsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, IFormCollection collection)
        {
            HttpResponseMessage res = await _httpClient.DeleteAsync($"{NewsApiUrl}/{id}");
            if (res.IsSuccessStatusCode)
            {
                SetAlert("News deleted successfully", "success");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", "Error while call Web API");
            }
            return RedirectToAction(nameof(Index));
        }
        #endregion

        // GET: DeleteId
        #region DeleteId
        [HttpPost]
        public async Task<JsonResult> DeleteId(int id)
        {
            try
            {
                HttpResponseMessage responseMessage = await _httpClient.DeleteAsync($"{NewsApiUrl}/{id}");
                HttpResponseMessage responseMessageData = await _httpClient.GetAsync(NewsApiUrl);
                var data = await responseMessageData.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };
                List<News> news = JsonSerializer.Deserialize<List<News>>(data, options);

WebMVC/Areas/Admin/Views/NewsAdmin/Create.cshtml
@model ObjectBussiness.NewsImage

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<style>
    label {
        color: black;
    }
</style>
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-md-4">
            @using (Html.BeginForm("Create", "NewsAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "alert alert-block alert-danger fade in" })
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    @Html.LabelFor(n => n.Title)
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Pleate enter title" } })

                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.Contents)
                    @Html.TextAreaFor(model => model.Contents, new { @class = "form-control", id = "summernote" })
                    @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.ShortContents)
                    @Html.EditorFor(model => model.ShortContents, new { htmlAttributes = new { @class = "form-control", @placeholder = "Pleate enter short contents" } })
                    <span asp-validation-for="ShortContents" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.ImageFile)
                    @Html.EditorFor(model => model.ImageFile, new { htmlAttributes = new { @class = "form-control", @placeholder = "Pleate choose image upload" } })
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.DateSubmitted)
                    @Html.EditorFor(model => model.DateSubmitted, new { htmlAttributes = new { @class = "form-control", @placeholder = "Pleate enter Date Publish" } })
                    <span asp-validation-for="DateSubmitted" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="CategoryID" class="control-label">News Category</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.CategoryID, ViewBag.Items as IEnumerable<SelectListItem>?? Enumerable.Empty<SelectListItem>(), "Choose an category", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.AccountID)
                    @Html.EditorFor(model => model.AccountID, new { htmlAttributes = new { @class = "form-control", @placeholder = "Please enter AccountID", @Value = "1" } })
                    <span asp-validation-for="AccountID" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Creat" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
    <br />

    <div>
        @Html.ActionLink("Back To List", "Index", "NewsAdmin", null, new { @class = "btn btn-danger" })
    </div>
</div>


<!--Kích hoạt phần tử #Content là Editor HTML -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>

<script>
    $('#summernote').summernote({
        placeholder: 'Enter News content',
        tabsize: 2,
        height: 120,
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });
</script>

WebMVC/Areas/Admin/Views/NewsAdmin/Edit.cshtml
@model ObjectBussiness.News

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-md-4">

            @using (Html.BeginForm("Edit", "NewsAdmin", FormMethod.Post))
            {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    @Html.LabelFor(n => n.NewsID)
                    @Html.EditorFor(model => model.NewsID, new { htmlAttributes = new { @class = "form-control",  @readonly = true } })
                    <span asp-validation-for="NewsID" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.Title)
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.Contents)
                    @Html.TextAreaFor(model => model.Contents, new { @class = "form-control", id = "summernote" })
                    @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.ShortContents)
                    @Html.EditorFor(model => model.ShortContents, new { htmlAttributes = new { @class = "form-control" } })
                    <span asp-validation-for="ShortContents" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">Avatar</label>
                    @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    <span asp-validation-for="Picture" class="text-danger"></span>
                    <img class="img-fluid" src="~/images/@Model.Picture" style="object-fit:cover; height:50px; width:50px">
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="CategoryID" class="control-label">News Category</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.CategoryID, ViewBag.Items as IEnumerable<SelectListItem>?? Enumerable.Empty<SelectListItem>(), "Choose an category", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(n => n.AccountID)
                    @Html.EditorFor(model => model.AccountID, new { htmlAttributes = new { @class = "form-control", @Value = "1", @readonly = true } })
                    <span asp-validation-for="AccountID" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
    <br />

    <div>
        @Html.ActionLink("Back To List", "Index", "NewsAdmin", null, new { @class = "btn btn-danger" })
    </div>
</div>
<!--Kích hoạt phần tử #Content là Editor HTML -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>

<script>
    $('#summernote').summernote({
        placeholder: 'Enter News content',
        tabsize: 2,
        height: 120,
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });
</script>

WebMVC/Areas/Admin/Views/NewsAdmin/Index.cshtml
@using ObjectBussiness;
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model IEnumerable<ObjectBussiness.News>

@{
    ViewData["Title"] = "News";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="container-fluid py-4">

    <p>
        <a style="color:black;background-color:yellow" class="btn" href="~/Admin/NewsAdmin/Create">Create New</a>
    </p>
    <div class="text-align">
        @if (TempData["AlertMessage"] != null)
        {
            <div id="AlertBox" class="alert @TempData["AlertType"]">

                @TempData["AlertMessage"]
            </div>
        }
    </div>
    <br />

    @using (Html.BeginForm("Index", "NewsAdmin", FormMethod.Get))
    {
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header pb-0">
                        <h6>News table</h6>
                    </div>
                    <div class="card-body px-0 pt-0 pb-2">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                                <thead>
                                    <tr>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            @Html.DisplayNameFor(model => model.NewsID)
                                        </th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            @Html.DisplayNameFor(model => model.Title)
                                        </th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            @Html.DisplayNameFor(model => model.ShortContents)
                                        </th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            @Html.DisplayNameFor(model => model.Picture)

                                        </th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            @Html.DisplayNameFor(model => model.DateSubmitted)
                                        </th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            @Html.DisplayNameFor(model => model.CategoryName)
                                        </th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            @Html.DisplayNameFor(model => model.Account)
                                        </th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.NewsID)</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.Title)</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.ShortContents)</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <img class="img-fluid" src="~/images/@item.Picture" style="object-fit:cover; height:50px; width:50px">
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">@Convert.ToDateTime(item.DateSubmitted).ToString("dd/MM/yyyy")</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">
                                                            @Html.DisplayFor(modelItem => item.CategoryName)
                                                        </h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.AccountName)</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div>
                                                    <button type="button" class="btn btn-success">@Html.ActionLink("Update", "Edit", new { id = item.NewsID })</button>&nbsp;
                                                    <a href="#" class="delete-link btn btn-danger" data-id="@item.NewsID" data-confirm="Do you really want to delete it?" data-toggle="modal" data-target="#confirmModal">Delete</a>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmModalLabel">Confirm Delete</h5>
                    </div>
                    <div class="modal-body">
                        <p id="confirmMessage"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    }
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page, SearchString = @Context.Request.Query["SearchString"] }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" }
    })
</div>

@section Scripts {

    <script type="text/javascript">
        function DisplayProgressMessage(ctl, msg) {
            //if use the submit button, you can use event.preventDefault to prevent the default submit form behavior.
            event.preventDefault();
            // Turn off the "Save" button and change text
            $(ctl).prop("disabled", true).val(msg);
            // Gray out background on page
            $("body").addClass("submit-progress-bg");
            // Wrap in setTimeout so the UI can update the spinners
            $(".processing-preview").removeClass("hidden");
            //submit the form.
            setTimeout(function () {
                $("form").submit();
            }, 3000);
            return true;
        }

        //Delete popup
        $(document).on("click", ".delete-link", function (e) {
            e.preventDefault();
            var id = $(this).data("id");
            var confirmMessage = $(this).data("confirm");

            $("#confirmMessage").text(confirmMessage);
            $("#confirmDelete").data("id", id);

            $("#confirmModal").modal("show");
        });

        $(document).on("click", "#confirmDelete", function (e) {
            e.preventDefault();
            var id = $(this).data("id");
            $.ajax({
                url: "/Admin/NewsAdmin/DeleteId/" + id,
                dataType: "json",
                type: "POST",
                contentType: "application/json;charset=UTF-8",
                success: function (res) {
                    if (res.status == true) {
                        window.location.href = '/Admin/NewsAdmin';
                    }
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
            //}
        });

    </script>
}